// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pet_Health_Tracker;

namespace Pet_Health_Tracker.Migrations
{
    [DbContext(typeof(PetTrackerContext))]
    [Migration("20211123195944_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pet_Health_Tracker.Models.MedicalItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MedicalRecordId")
                        .HasColumnType("int");

                    b.Property<int>("RecordType")
                        .HasColumnType("int");

                    b.Property<DateTime>("TreatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MedicalRecordId");

                    b.ToTable("MedicalItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cras eu malesuada lectus. Suspendisse vel mattis magna.",
                            MedicalRecordId = 1,
                            RecordType = 0,
                            TreatedOn = new DateTime(2021, 11, 23, 14, 59, 43, 335, DateTimeKind.Local).AddTicks(5256)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cras eu malesuada lectus. Suspendisse vel mattis magna.",
                            MedicalRecordId = 2,
                            RecordType = 1,
                            TreatedOn = new DateTime(2021, 11, 23, 14, 59, 43, 339, DateTimeKind.Local).AddTicks(4955)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cras eu malesuada lectus. Suspendisse vel mattis magna.",
                            MedicalRecordId = 3,
                            RecordType = 2,
                            TreatedOn = new DateTime(2021, 11, 23, 14, 59, 43, 339, DateTimeKind.Local).AddTicks(5062)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Cras eu malesuada lectus. Suspendisse vel mattis magna.",
                            MedicalRecordId = 1,
                            RecordType = 3,
                            TreatedOn = new DateTime(2021, 11, 23, 14, 59, 43, 339, DateTimeKind.Local).AddTicks(5071)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Cras eu malesuada lectus. Suspendisse vel mattis magna.",
                            MedicalRecordId = 2,
                            RecordType = 4,
                            TreatedOn = new DateTime(2021, 11, 23, 14, 59, 43, 339, DateTimeKind.Local).AddTicks(5075)
                        },
                        new
                        {
                            Id = 6,
                            Description = "Cras eu malesuada lectus. Suspendisse vel mattis magna.",
                            MedicalRecordId = 3,
                            RecordType = 5,
                            TreatedOn = new DateTime(2021, 11, 23, 14, 59, 43, 339, DateTimeKind.Local).AddTicks(5080)
                        });
                });

            modelBuilder.Entity("Pet_Health_Tracker.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("MedicalRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PetId = 1
                        },
                        new
                        {
                            Id = 2,
                            PetId = 2
                        },
                        new
                        {
                            Id = 3,
                            PetId = 3
                        });
                });

            modelBuilder.Entity("Pet_Health_Tracker.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Dan",
                            LastName = "Fairchild"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Kevin",
                            LastName = "Tousey"
                        });
                });

            modelBuilder.Entity("Pet_Health_Tracker.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 7,
                            Breed = "Husky Mix",
                            Gender = "Male",
                            Name = "Brewster",
                            OwnerId = 1,
                            Photo = "",
                            Species = "Dog"
                        },
                        new
                        {
                            Id = 2,
                            Age = 6,
                            Breed = "Maltese",
                            Gender = "Female",
                            Name = "Princess Trudy",
                            OwnerId = 2,
                            Photo = "",
                            Species = "Dog"
                        },
                        new
                        {
                            Id = 3,
                            Age = 2,
                            Breed = "Black Sable",
                            Gender = "Male",
                            Name = "Slim Jim",
                            OwnerId = 1,
                            Photo = "",
                            Species = "Ferret"
                        });
                });

            modelBuilder.Entity("Pet_Health_Tracker.Models.Weight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentWeight")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("Weight");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentWeight = 50,
                            DateTime = new DateTime(2021, 11, 23, 14, 59, 43, 339, DateTimeKind.Local).AddTicks(6775),
                            PetId = 1
                        },
                        new
                        {
                            Id = 2,
                            CurrentWeight = 12,
                            DateTime = new DateTime(2021, 11, 23, 14, 59, 43, 339, DateTimeKind.Local).AddTicks(7347),
                            PetId = 2
                        },
                        new
                        {
                            Id = 3,
                            CurrentWeight = 2,
                            DateTime = new DateTime(2021, 11, 23, 14, 59, 43, 339, DateTimeKind.Local).AddTicks(7357),
                            PetId = 3
                        });
                });

            modelBuilder.Entity("Pet_Health_Tracker.Models.MedicalItem", b =>
                {
                    b.HasOne("Pet_Health_Tracker.Models.MedicalRecord", "Record")
                        .WithMany("MedicalItems")
                        .HasForeignKey("MedicalRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("Pet_Health_Tracker.Models.MedicalRecord", b =>
                {
                    b.HasOne("Pet_Health_Tracker.Models.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Pet_Health_Tracker.Models.Pet", b =>
                {
                    b.HasOne("Pet_Health_Tracker.Models.Owner", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Pet_Health_Tracker.Models.Weight", b =>
                {
                    b.HasOne("Pet_Health_Tracker.Models.Pet", "Pet")
                        .WithMany("Weights")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Pet_Health_Tracker.Models.MedicalRecord", b =>
                {
                    b.Navigation("MedicalItems");
                });

            modelBuilder.Entity("Pet_Health_Tracker.Models.Owner", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("Pet_Health_Tracker.Models.Pet", b =>
                {
                    b.Navigation("Weights");
                });
#pragma warning restore 612, 618
        }
    }
}
